spring:
  jpa:
    show-sql: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  config: classpath:logback-local.xml